Update build-kernel_by_clang383902b.yml

diff --git a/.github/workflows/build-kernel_by_clang383902b.yml b/.github/workflows/build-kernel_by_clang383902b.yml
--- a/.github/workflows/build-kernel_by_clang383902b.yml
+++ b/.github/workflows/build-kernel_by_clang383902b.yml
@@ -189,6 +189,12 @@ jobs:
     - name: Build kernel
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
+
+        # check .config location...
+        echo check config
+        ls -la out/.config || echo "out config NOT FOUND"
+        ls -la .config || echo "root config NOT FOUND"
+        
         export PATH=$GITHUB_WORKSPACE/kernel_workspace/clang-aosp/google_clang/clang-r383902b-11.0.2/bin:$GITHUB_WORKSPACE/kernel_workspace/clang-aosp/google_gcc/aarch64-linux-android-4.9/bin:$GITHUB_WORKSPACE/kernel_workspace/clang-aosp/google_gcc/arm-linux-androideabi-4.9/bin:$PATH
         export KBUILD_BUILD_HOST=Github-Action
         export KBUILD_BUILD_USER=$(echo ${{ github.actor }} | tr A-Z a-z)
